### ISSUE TITLE
fill out the email to pi about  submissions needing attention

### ISSUE THREAD

**Issue by htpvu** [DataConservancy/pass-ember#24]
include all submission within a grant.

**Comment by htpvu** [comment]
![screen shot 2017-12-05 at 3 15 42 pm](https://user-images.githubusercontent.com/11050142/33628677-8e930d16-d9cf-11e7-872f-87a101032f0e.png)

**Comment by markpatton** [comment]
Message text:

Submission title: <title>
The status of the article is <status> Please check on your Pass dashboard.

**Comment by markpatton** [comment]
Mistook this issue for #36 and closed prematurely.
