### ISSUE TITLE
update the message for contacting corr. author in the submisisions table

### ISSUE THREAD

**Issue by htpvu** [DataConservancy/pass-ember#36]

**Comment by htpvu** [comment]
![screen shot 2017-12-05 at 3 15 42 pm](https://user-images.githubusercontent.com/11050142/33630396-33025604-d9d5-11e7-86d7-0e9c4802898d.png)

**Comment by markpatton** [comment]
Many to many relationship between a grant and submissions. The semantics of this request are unclear.
