### ISSUE TITLE
Layout issue on the submission's journal selection modal pop up 

### ISSUE THREAD

**Issue by htpvu** [DataConservancy/pass-ember#62]
<img width="771" alt="screen shot 2017-12-09 at 2 19 46 pm" src="https://user-images.githubusercontent.com/11050142/33798741-26f929cc-dcec-11e7-8916-9c8606bfea98.png">

**Comment by birkland** [comment]
@htpvu This can happen if the screen is too small horizontally.  Need to figure out how to make the white background grow horizontally in css, or maybe use bootstrap4 built-in modals rather than `ember-modal-dialog`.

**Comment by markpatton** [comment]
You can also probably group the buttons together with https://getbootstrap.com/docs/4.0/components/button-group/

**Comment by birkland** [comment]
The `message-dialog` popup (for e-mailing corr. authors in the grants table) doesn't have this issue; it looks like it achieves this by having a fixed pixel width element in it...

**Comment by markpatton** [comment]
Right. As a bad hack, I just set the width.

**Comment by jabrah** [comment]
@htpvu 
Do we want to make the modal grow in size to accommodate the buttons? Or should we change the layout of the buttons to prevent this behavior?

The buttons show similar behavior in small screens in other places as well, from dashboard > View Submissions > Create New Submission > Next

![image](https://user-images.githubusercontent.com/5167587/33842376-566b99a6-de68-11e7-8084-3294cd837103.png)

Changing the button layout in the modal would also change the button layout in this new submission screen, as well as other screens in the submission workflow.

![image](https://user-images.githubusercontent.com/5167587/33842581-ec5ed522-de68-11e7-8a82-385ce0b7eb68.png)

**Comment by htpvu** [comment]
Let's change the out of the buttons! @jabrah

**Comment by jabrah** [comment]
Mostly taken care of by PR https://github.com/DataConservancy/pass-ember/pull/78
New issue created to address MS Edge layout
