### ISSUE TITLE
Lay out issues with some pages in the Submission workflow

### ISSUE THREAD

**Issue by htpvu** [DataConservancy/pass-ember#77]
if you go through the submission workflow, you'd note the UI elements in Compliance and Repositories page are squished up together with no vertical spaces between elements.

**Comment by htpvu** [comment]
<img width="908" alt="screen shot 2017-12-11 at 11 53 47 am" src="https://user-images.githubusercontent.com/11050142/33843060-4bc97e4e-de6a-11e7-95e4-76615d6c4e1d.png">
![screen shot 2017-12-11 at 10 21 11 am](https://user-images.githubusercontent.com/11050142/33843070-5142aa94-de6a-11e7-9576-394fc772d97f.png)

**Comment by htpvu** [comment]
![screen shot 2017-12-11 at 10 21 11 am](https://user-images.githubusercontent.com/11050142/33843083-5b163720-de6a-11e7-951b-cd981fbffae8.png)

**Comment by jabrah** [comment]
Resolved with PR https://github.com/DataConservancy/pass-ember/pull/81
