### ISSUE TITLE
Button got too narrow when the window was resized to be too narrow. 

### ISSUE THREAD

**Issue by htpvu** [DataConservancy/pass-ember#86]
you can find this button in the Common-Metadata page. so the template should be named something like: submission-metadata-common.hbs.

**Comment by htpvu** [comment]
![screen shot 2017-12-12 at 10 21 28 am](https://user-images.githubusercontent.com/11050142/33892260-58fad4f2-df26-11e7-83c4-261b03dabdd1.png)

**Comment by jabrah** [comment]
Should address some minor layout issues with metadata panel with narrow width screen. None of these should be apparent with the demo

![image](https://user-images.githubusercontent.com/5167587/33893413-5676e10a-df29-11e7-8476-444bd6a7222c.png)
